# 공통만 정의할 것
spring:
  profiles:
    active: local

# 공통 정의 영역
# 블라블라..
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 9000

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 9001
